# Generated by Django 4.1.6 on 2023-02-27 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_catagory_product_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='catagory',
        ),
    ]
